name: mbus
description: "A new Flutter mbus package project."
version: 0.1.1
homepage: https://github.com/msfm2018/mbus
repository: https://github.com/msfm2018/mbus

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

