name: mbus
description: A lightweight and efficient event bus system for Flutter applications. Provides simple event-driven architecture with support for module-based event management and global event broadcasting.
version: 0.1.1
homepage: https://github.com/msfm2018/mbus
repository: https://github.com/msfm2018/mbus
issue_tracker: https://github.com/msfm2018/mbus/issues
documentation: https://pub.dev/packages/mbus

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
example: example/lib/main.dart
topics:
  - event-bus
  - event-driven
  - state-management
  - messaging
  - flutter
